services:
  mysql:
    image: mysql:8.4
    container_name: vibr-mysql
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'vibr'
      TZ: 'UTC'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1', '-u', 'root', '-p1234']
      interval: 5s
      timeout: 3s
      retries: 20
