services:
  redis:
    image: redis:8.4-alpine
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}" ]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 20
  neo4j:
    image: neo4j:5.15
    container_name: vibr-neo4j
    ports:
      - "7474:7474" # HTTP (브라우저 콘솔용)
      - "7687:7687" # Bolt (애플리케이션 연결용)
    environment:
      NEO4J_AUTH: neo4j/1234
    volumes:
      - ./neo4j/data:/data
      retries: 10

volumes:
  redis-data:
